### ISSUE TITLE
warpctc_tensorflow/kernels.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

### ISSUE THREAD

**Issue by gccrpm** [baidu-research/warp-ctc#109]
Traceback (most recent call last):
  File "./lstm/train_net.py", line 13, in <module>
    from  lib.networks.factory import get_network
  File "./lstm/../lib/networks/__init__.py", line 1, in <module>
    from . import factory
  File "./lstm/../lib/networks/factory.py", line 11, in <module>
    from .LSTM_train import LSTM_train
  File "./lstm/../lib/networks/LSTM_train.py", line 2, in <module>
    from .network import Network
  File "./lstm/../lib/networks/network.py", line 6, in <module>
    import warpctc_tensorflow
  File "/usr/local/lib/python2.7/dist-packages/warpctc_tensorflow-0.1-py2.7-linux-x86_64.egg/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: /usr/local/lib/python2.7/dist-packages/warpctc_tensorflow-0.1-py2.7-linux-x86_64.egg/warpctc_tensorflow/kernels.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

how to solve this problem,any advice @jaredcasper   thank you!

**Comment by rolai** [comment]
I meet the same problem, is there any updates?
