### ISSUE TITLE
KeyError: "Registering two gradient with name 'WarpCTC' !(Previous registration was in setup /root/anaconda3/envs/tensorflow/lib/python3.6/distutils/core.py:148)"

### ISSUE THREAD

**Issue by gccrpm** [baidu-research/warp-ctc#111]
hi, when i install warp-ctc in anaconda3 ,i installed warp-ctc successfully,
but when i run python setup.py test , i got this error:

OK
test_ctc_loss_op (unittest.loader._FailedTest) ... ERROR
test_warpctc_op (unittest.loader._FailedTest) ... ERROR

======================================================================
ERROR: test_ctc_loss_op (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ctc_loss_op
Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/root/warp-ctc/tensorflow_binding/tests/test_ctc_loss_op.py", line 23, in <module>
    import warpctc_tensorflow
  File "/root/warp-ctc/tensorflow_binding/warpctc_tensorflow/__init__.py", line 47, in <module>
    @ops.RegisterGradient("WarpCTC")
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2256, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'WarpCTC' !(Previous registration was in setup /root/anaconda3/envs/tensorflow/lib/python3.6/distutils/core.py:148)"

======================================================================
ERROR: test_warpctc_op (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_warpctc_op
Traceback (most recent call last):
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/root/warp-ctc/tensorflow_binding/tests/test_warpctc_op.py", line 3, in <module>
    from warpctc_tensorflow import ctc
  File "/root/warp-ctc/tensorflow_binding/warpctc_tensorflow/__init__.py", line 47, in <module>
    @ops.RegisterGradient("WarpCTC")
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2256, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/root/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'WarpCTC' !(Previous registration was in setup /root/anaconda3/envs/tensorflow/lib/python3.6/distutils/core.py:148)"

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>

ps: i have test in python2.7 , have no this  error

anyone can give some advice? thank you  ! @jaredcasper

**Comment by afterimagex** [comment]
i had the same error, can you tell me how did you solvered it?

ERROR: test_ctc_loss_op (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ctc_loss_op
Traceback (most recent call last):
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/disk1/xupeichao/CTC/warp-ctc-baidu/tensorflow_binding/tests/test_ctc_loss_op.py", line 23, in <module>
    import warpctc_tensorflow
  File "/home/disk1/xupeichao/CTC/warp-ctc-baidu/tensorflow_binding/warpctc_tensorflow/__init__.py", line 37, in <module>
    @ops.RegisterGradient("WarpCTC")
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1788, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'WarpCTC' !(Previous registration was in run_commands /home/xupeichao/.conda/envs/tf13/lib/python3.5/distutils/dist.py:955)"


======================================================================
ERROR: test_warpctc_op (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_warpctc_op
Traceback (most recent call last):
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/home/disk1/xupeichao/CTC/warp-ctc-baidu/tensorflow_binding/tests/test_warpctc_op.py", line 3, in <module>
    from warpctc_tensorflow import ctc
  File "/home/disk1/xupeichao/CTC/warp-ctc-baidu/tensorflow_binding/warpctc_tensorflow/__init__.py", line 37, in <module>
    @ops.RegisterGradient("WarpCTC")
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1788, in __call__
    _gradient_registry.register(f, self._op_type)
  File "/home/xupeichao/.conda/envs/tf13/lib/python3.5/site-packages/tensorflow/python/framework/registry.py", line 62, in register
    (self._name, name, function_name, filename, line_number))
KeyError: "Registering two gradient with name 'WarpCTC' !(Previous registration was in run_commands /home/xupeichao/.conda/envs/tf13/lib/python3.5/distutils/dist.py:955)"


----------------------------------------------------------------------
Ran 2 tests in 0.000s

FAILED (errors=2)
Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=2 errors=2 failures=0>
