### ISSUE TITLE
"No module named kernels" when test

### ISSUE THREAD

**Issue by XiongChengxin** [baidu-research/warp-ctc#134]
I install tensorflow by anaconda, and successfully install warpctc-tensorflow, i.e. it would show "warpctc-tensorflow" when I run the command "conda list". But I would meet the error when test. Any ideas?

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "warpctc_tensorflow/__init__.py", line 6, in <module>
    lib_file = imp.find_module('kernels', __path__)[1]
ImportError: No module named kernels

"kernels" can't be installed by pip or conda.

**Comment by XiongChengxin** [comment]
Solved. Modified parameter "lib_file" of file warpctc_tensorflow/**init**.py to the real path of kernels.so. For me, "lib_file = '../warp-ctc/tensorflow_binding/build/lib.linux-x86_64-2.7/warpctc_tensorflow/kernels.so'". Then it won't meet the above error.
