### ISSUE TITLE
TF binding not working on tensorflow tensorflow-gpu (1.1.0)

### ISSUE THREAD

**Issue by ltn614** [baidu-research/warp-ctc#80]
I am facing the problem, I tried set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GLIBCXX_USE_CXX11_ABI=0") in CmakeList file, it doesn't work, also tried add -D_GLIBCXX_USE_CXX11_ABI=0 in setup.py, it doesn't work too, I paste my error message:

python lstm_warpCTC.py
Traceback (most recent call last):
  File "lstm_warpCTC.py", line 10, in <module>
    import warpctc_tensorflow
  File "/home/jason/anaconda3/lib/python3.5/site-packages/warpctc_tensorflow-0.1-py3.5-linux-x86_64.egg/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/home/jason/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/jason/anaconda3/lib/python3.5/site-packages/warpctc_tensorflow-0.1-py3.5-linux-x86_64.egg/warpctc_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_

**Comment by wellescastro** [comment]
+1

**Comment by stefbraun** [comment]
+1

**Comment by Elizabethcase** [comment]
+1

**Comment by dieka13** [comment]
+1

**Comment by shahinkl** [comment]
+1

**Comment by matth** [comment]
Ensure you delete the `build` and `dist` directories in the `tensorflow_binding` directory after applying fix, works for me

**Comment by freesouls** [comment]
happend to see the same problem when binding with tf 1.1.0,  though `python setup.py test` can not run correctly, but I can still use warp-ctc by installing `python setup.py install`, it seems it does not affect the results
