### ISSUE TITLE
import warpctc_tensorflow error::kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol:

### ISSUE THREAD

**Issue by gnnbest** [baidu-research/warp-ctc#92]
run python setup.py install is ok but when I ran python setup.py test it had errors::
I used python3 and tensorflow 1.3.0 gpu version

Traceback (most recent call last):
  File "lstm_warpCTC.py", line 10, in <module>
    import warpctc_tensorflow
  File "/home/gunn/.local/lib/python3.5/site-packages/warpctc_tensorflow-0.1-py3.5-linux-x86_64.egg/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/home/gunn/.local/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /home/gunn/.local/lib/python3.5/site-packages/warpctc_tensorflow-0.1-py3.5-linux-x86_64.egg/warpctc_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow14TensorShapeRep11DebugStringB5cxx11Ev

**Comment by nickwind** [comment]
same issue for me

**Comment by Sherry-Zhang** [comment]
similar issue for me, too.
tensorflow.python.framework.errors_impl.NotFoundError: /home/shuzhan1/workspace/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by baoniu** [comment]
me too ..

**Comment by vankrelian** [comment]
same

/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by wellescastro** [comment]
Same to me in TF 1.4

**Comment by struCoder** [comment]
```bash
tensorflow.python.framework.errors_impl.NotFoundError: /home/xx/ky/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZNK10tensorflow14TensorShapeRep11DebugStringB5cxx11Ev

```

TF: `1.3.0`

**Comment by standy66** [comment]
Passing
```
extra_link_args=['-L' + tf.sysconfig.get_lib(), '-ltensorflow_framework']
```
to `setuptools.Extension` parameters in `setup.py` works for me (TF 1.4)

**Comment by yudingling** [comment]
@standy66 did as you said, but another error appeared..

    import warpctc_tensorflow
  File "/home/zd/anaconda3/lib/python3.5/site-packages/warpctc_tensorflow-0.1-py3.5-linux-x86_64.egg/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/home/zd/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 56, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename, status)
  File "/home/zd/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: dlopen: cannot load any more object with static TLS

**Comment by huizhang0110** [comment]
same to me 
```
tensorflow.python.framework.errors_impl.NotFoundError: /home/zhui/src-code/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
```

**Comment by gccrpm** [comment]
anyone solved this problem? the same:
warpctc_tensorflow/kernels.so: undefined symbol: _ZTIN10tensorflow8OpKernelE

**Comment by engrean** [comment]
Same for me on tensorflow 1.7.0
kernels.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZTIN10tensorflow8OpKernelE
I am using anaconda.

**Comment by Sherry-Zhang** [comment]
I solved. Add 'tensorflow_framework' to libraries, the issue will be fixed.
```
ext = setuptools.Extension('warpctc_tensorflow.kernels',
                           sources = lib_srcs,
                           language = 'c++',
                           include_dirs = include_dirs,
                           library_dirs = [warp_ctc_path],
                           runtime_library_dirs = [os.path.realpath(warp_ctc_path)],
                           libraries = ['warpctc', 'tensorflow_framework'],
                           extra_compile_args = extra_compile_args)
```

**Comment by struCoder** [comment]
@Sherry-Zhang 
I installed tensorflow by pip, follow your steps i got this wrong:
`can not foud -ltensorflow_framework`

**Comment by Sherry-Zhang** [comment]
@struCoder it only works when you build tensorflow by source

**Comment by TheJaeLal** [comment]
I build tensorflow 1.7 from source and still it didn't work

**Comment by JansonJo** [comment]
ME TOO
pytorch: 0.4
python: 3.6

ImportError: /home/jayson/anaconda3/envs/ml/lib/python3.6/site-packages/warpctc_pytorch-0.1-py3.6-linux-x86_64.egg/warpctc_pytorch/_warp_ctc.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE
