### ISSUE TITLE
Finished processing dependencies for warpctc-tensorflow==0.1, but test error

### ISSUE THREAD

**Issue by flystarhe** [baidu-research/warp-ctc#98]
```
======================================================================
ERROR: test_ctc_loss_op (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_ctc_loss_op
Traceback (most recent call last):
  File "/root/anaconda3/lib/python3.5/unittest/loader.py", line 428, in _find_test_path
    module = self._get_module_from_name(name)
  File "/root/anaconda3/lib/python3.5/unittest/loader.py", line 369, in _get_module_from_name
    __import__(name)
  File "/data2/apps/warp-ctc/tensorflow_binding/tests/test_ctc_loss_op.py", line 23, in <module>
    import warpctc_tensorflow
  File "/data2/apps/warp-ctc/tensorflow_binding/warpctc_tensorflow/__init__.py", line 7, in <module>
    _warpctc = tf.load_op_library(lib_file)
  File "/root/anaconda3/lib/python3.5/site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
    None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: /data2/apps/warp-ctc/tensorflow_binding/warpctc_tensorflow/kernels.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_S3_S3_

```

**Comment by baoniu** [comment]
me too

**Comment by baoniu** [comment]
百度的工程师可否帮忙解决一下

**Comment by vankrelian** [comment]
same

**Comment by deepfinch** [comment]
The python wrap file '_pywrap_tensorflow_internal.so' doesn't contain symbol '_ZN10tensorflow7strings6StrCatB5cxx11ERKNS0_8AlphaNumES3_S3_S3_'
Did you installed an online tensorflow by conda or pip ?
You should build tensorflow from source code, and install by command: `pip install /your/local/path/target-tensorflow-version.whl`。
Then this error can be fixed.
